export const subjectData = {
  DBMS:{code:"DBMS",name:"Database Management Systems",description:"Database Management Systems (DBMS) covers the concepts of data models, relational databases, SQL, normalization, transaction management and database design.",semester:"VI",branch:"Computer Engineering",university:"Savitribai Phule Pune University (SPPU)",credits:4,rating:"4.7",stats:{total:42,pyqs:12,notes:9,practicals:7,books:5,other:9},distribution:[["Notes",9,"21%"],["PYQs",12,"29%"],["Practicals",7,"17%"],["Books",5,"12%"],["Others",9,"21%"]],topics:[["Normalization",28],["SQL Queries",24],["Transaction Management",18],["ER Diagram",16],["Concurrency Control",14]],resources:[
["DBMS Complete Notes (All Units)","Complete handwritten notes covering all units with diagrams and examples.","Unit I–V","2.4 MB","4.8","320","1.2K downloads","Notes","Complete","cream"],
["Unit I - Introduction to DBMS","Overview, DBMS architecture, data models, schemas.","Unit I","1.1 MB","4.6","210","890 downloads","Notes","Unit Wise","blue"],
["Unit II - Relational Model & Normalization","Detailed relational algebra, normalization with examples.","Unit II","1.8 MB","4.7","430","1.4K downloads","Notes","Important","red"],
["Unit III - SQL and PL/SQL","SQL queries, functions, procedures with examples.","Unit III","1.6 MB","4.5","190","760 downloads","Notes","Code Examples","green"],
["Unit IV - Transaction Management","ACID properties, concurrency control, recovery.","Unit IV","1.3 MB","4.6","280","980 downloads","Notes","Important","cream"],
["Unit V - File Organization & Indexing","File structures, indexing, hashing with solved examples.","Unit V","1.4 MB","4.4","160","690 downloads","Notes","Revision","blue"]]},
  OS:{code:"OS",name:"Operating Systems",description:"Operating Systems covers process management, memory management, scheduling, synchronization, file systems and system-level concepts.",semester:"VI",branch:"Computer Engineering",university:"Savitribai Phule Pune University (SPPU)",credits:4,rating:"4.6",stats:{total:36,pyqs:10,notes:8,practicals:6,books:4,other:8}},
  CN:{code:"CN",name:"Computer Networks",description:"Computer Networks covers networking models, protocols, routing, transport services, security and reliable communication.",semester:"VI",branch:"Computer Engineering",university:"Savitribai Phule Pune University (SPPU)",credits:4,rating:"4.7",stats:{total:51,pyqs:15,notes:12,practicals:8,books:5,other:11}},
  WT:{code:"WT",name:"Web Technologies",description:"Web Technologies brings together modern client-side and server-side concepts used to build responsive and interactive web applications.",semester:"VI",branch:"Computer Engineering",university:"Savitribai Phule Pune University (SPPU)",credits:4,rating:"4.5",stats:{total:28,pyqs:8,notes:7,practicals:5,books:3,other:5}},
  OOMD:{code:"OOMD",name:"Object Oriented Modeling & Design",description:"Study object-oriented analysis, design principles, UML models, relationships and software architecture concepts.",semester:"VI",branch:"Computer Engineering",university:"Savitribai Phule Pune University (SPPU)",credits:4,rating:"4.5",stats:{total:24,pyqs:6,notes:8,practicals:4,books:3,other:3}},
  STQA:{code:"STQA",name:"Software Testing & QA",description:"Learn software quality practices, test planning, test design, automation concepts and quality assurance techniques.",semester:"VI",branch:"Computer Engineering",university:"Savitribai Phule Pune University (SPPU)",credits:4,rating:"4.6",stats:{total:20,pyqs:7,notes:5,practicals:3,books:2,other:3}},
  CC:{code:"CC",name:"Cloud Computing",description:"Explore cloud service models, virtualization, deployment models, cloud architecture, security and practical cloud platforms.",semester:"VI",branch:"Computer Engineering",university:"Savitribai Phule Pune University (SPPU)",credits:4,rating:"4.5",stats:{total:26,pyqs:8,notes:6,practicals:3,books:4,other:5}},
  AI:{code:"AI",name:"Artificial Intelligence",description:"Explore artificial intelligence fundamentals, search, knowledge representation, machine learning concepts and intelligent systems.",semester:"VI",branch:"Computer Engineering",university:"Savitribai Phule Pune University (SPPU)",credits:4,rating:"4.7",stats:{total:18,pyqs:5,notes:5,practicals:4,books:2,other:2}}
};
const genericTopics={OS:["Process Scheduling","Process Synchronization","Memory Management","Deadlocks","File Systems"],CN:["TCP/IP","Routing","Transport Layer","Network Security","Congestion Control"],WT:["HTML & CSS","JavaScript","DOM","React","Web Services"],OOMD:["UML Diagrams","Use Case Modeling","Class Diagrams","Design Patterns","Object Design"],STQA:["Test Planning","Test Cases","Automation Testing","Quality Assurance","Defect Management"],CC:["Virtualization","Cloud Service Models","Deployment Models","Cloud Security","Cloud Architecture"],AI:["Search Algorithms","Knowledge Representation","Machine Learning","Expert Systems","Neural Networks"]};
export function getSubject(code){
 const subject=subjectData[code]||subjectData.DBMS;
 if(subject.resources)return subject;
 const topics=(genericTopics[subject.code]||["Unit I Concepts","Core Fundamentals","Important Questions","Practical Concepts","Exam Revision"]).map((name,i)=>[name,Math.max(4,subject.stats.notes+subject.stats.pyqs-i*2)]);
 const units=["I","I","II","III","IV","V"];
 const resources=["Complete Notes (All Units)","Unit I - Fundamentals","Unit II - Core Concepts","Unit III - Important Concepts","Unit IV - Advanced Topics","Unit V - Revision Notes"].map((title,i)=>[subject.code+" - "+title,"Organized "+subject.name.toLowerCase()+" notes with explanations, diagrams and examples.","Unit "+units[i],(1.1+i*.2).toFixed(1)+" MB",(4.4+i*.1).toFixed(1),String(150+i*35),(520+i*80)+" downloads","Notes",i===0?"Complete":"Unit Wise",i%3===0?"cream":i%3===1?"blue":"green"]);
 const dist=[["Notes",subject.stats.notes],["PYQs",subject.stats.pyqs],["Practicals",subject.stats.practicals],["Books",subject.stats.books],["Others",subject.stats.other]];
 return {...subject,topics,resources,distribution:dist.map(x=>[x[0],x[1],Math.round(x[1]/subject.stats.total*100)+"%"])};
}
