import {useMemo,useState} from "react";
import {FiBookmark,FiBookOpen,FiCalendar,FiChevronDown,FiDownload,FiFileText,FiGrid,FiMaximize,FiMessageSquare,FiPrinter,FiRotateCw,FiSearch,FiShare2,FiStar,FiUser,FiZoomIn,FiZoomOut,FiChevronUp} from "react-icons/fi";
import {Link,useParams} from "react-router-dom";
import HomeNavbar from "../home/components/HomeNavbar";
import {getSubject} from "../subjects/subjectData";
import "../../styles/resource-viewer.css";

const slugify=value=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
function buildViewerResource(subject,resourceId){
 const resources=subject.resources||[];
 const index=resources.findIndex(r=>slugify(r[0])===resourceId);
 const item=index>=0?resources[index]:resources[0];
 if(!item)return {title:"Study Resource",description:subject.description,unit:"Unit I",size:"1.8 MB",rating:subject.rating,reviews:"120",downloads:"890",type:"Notes"};
 return {title:item[0],description:item[1],unit:item[2],size:item[3],rating:item[4],reviews:item[5],downloads:item[6],type:item[7],index:index<0?0:index};
}
function DocumentPreview({subject,resource,page,setPage}){
 const [zoom,setZoom]=useState(100); const isDbms=subject.code==="DBMS";
 const sections=isDbms?[["2.1","Relational Model","A relational model represents data in the form of tables (relations).","Each table consists of rows (tuples) and columns (attributes).","It provides a simple and intuitive way to organize and access data.","Proposed by E. F. Codd in 1970."],["2.2","Keys in Relational Model","Super Key: A set of attributes that uniquely identifies a tuple.","Candidate Key: A minimal super key.","Primary Key: Selected candidate key.","Foreign Key: Attribute that references primary key of another relation."]]:[["1.1","Core Concepts","This section introduces the fundamental concepts and terminology of the subject.","Understand the core definitions, models and practical concepts before moving ahead.","Use examples and diagrams to reinforce your understanding.","Review the important points at the end of the unit."]];
 const title=isDbms?"Relational Model & Normalization":resource.title.replace(/^.*?-s*/,"");
 return <div className="document-frame"><div className="document-toolbar"><div className="document-tools-left"><button><FiGrid/></button><button><FiFileText/></button><button><FiSearch/></button><span className="toolbar-divider"/><button onClick={()=>setPage(Math.max(1,page-1))}><FiChevronUp/></button><button onClick={()=>setPage(Math.min(62,page+1))}><FiChevronDown/></button><span className="page-counter">{page} / 62</span><span className="toolbar-divider"/></div><div className="document-tools-right"><button onClick={()=>setZoom(Math.max(70,zoom-10))}><FiZoomOut/></button><span>{zoom}%</span><button onClick={()=>setZoom(Math.min(130,zoom+10))}><FiZoomIn/></button><span className="toolbar-divider"/><button><FiMaximize/></button><button><FiRotateCw/></button><button><FiDownload/></button><button><FiPrinter/></button><button><FiMaximize/></button></div></div><div className="document-stage"><article className="document-page" style={{transform:"scale("+zoom/100+")",transformOrigin:"top center"}}><div className="document-unit">Unit {isDbms?"II":"I"}</div><h1>{title}</h1><div className="document-rule"/>{sections.map(([num,heading,...lines])=><section className="document-section" key={num}><h2><span>{num}</span> {heading}</h2><ul>{lines.map(line=><li key={line}>{line}</li>)}</ul>{isDbms&&num==="2.1"&&<div className="student-table"><strong>Student Table (Relation)</strong><table><thead><tr><th>Roll_No</th><th>Name</th><th>Branch</th><th>Year</th></tr></thead><tbody><tr><td>101</td><td>Aarti</td><td>Computer</td><td>3</td></tr><tr><td>102</td><td>Rahul</td><td>IT</td><td>3</td></tr><tr><td>103</td><td>Sneha</td><td>Computer</td><td>3</td></tr></tbody></table><small>Tuple (Row) → Attribute (Column)</small></div>}</section>)}<div className="document-section"><h2>Practice & Revision</h2><p>Use the examples in this unit to revise the important concepts and prepare for university examinations.</p></div></article></div><div className="document-statusbar"><span><FiFileText/> {resource.title}.pdf</span><span>{page} / 62</span><span>{resource.size}</span><button><FiMaximize/></button></div></div>
}
function Outline({subject}){
 const sections=subject.code==="DBMS"?[["1. Introduction",["1.1  Database System","1.2  File System vs DBMS","1.3  Advantages of DBMS"],"1"],["2. Relational Model",["2.1  Structure","2.2  Keys","2.3  Relational Algebra"],"5"],["3. Normalization",["3.1  Functional Dependency","3.2  1NF","3.3  2NF","3.4  3NF","3.5  BCNF"],"12"],["4. Examples",[],"30"],["5. Practice Questions",[],"38"]]:[["1. Introduction",["1.1  Overview","1.2  Core Concepts","1.3  Architecture"],"1"],["2. Fundamentals",["2.1  Basic Concepts","2.2  Important Models","2.3  Key Terminology"],"6"],["3. Practical Concepts",["3.1  Examples","3.2  Problem Solving","3.3  Revision"],"14"],["4. Examples",[],"28"],["5. Practice Questions",[],"36"]];
 return <aside className="viewer-outline"><div className="outline-tabs"><button className="active">Outline</button><button>Thumbnails</button><button>Bookmarks</button></div><div className="outline-tree">{sections.map(([title,children,page],i)=><div className="outline-group" key={title}><button className="outline-heading"><FiChevronDown/><b>{title}</b><span>{page}</span></button>{children.map((child,j)=><button className="outline-child" key={child}><span>{child}</span><em>{Number(page)+j+1}</em></button>)}</div>)}</div><button className="document-search"><FiSearch/> Search in Document</button></aside>
}
function ReadingProgress({page}){
 const [complete,setComplete]=useState(false),[saved,setSaved]=useState(false),progress=Math.round(page/62*100);
 return <aside className="viewer-right"><section className="viewer-side-card reading-card"><h3><FiFileText/> Reading Progress</h3><div className="reading-progress"><div className="progress-ring" style={{"--progress":progress*3.6+"deg"}}><strong>{progress}%</strong></div><div><p>{page} of 62 pages</p><div className="thin-progress"><span style={{width:progress+"%"}}/></div></div></div><button className="complete-button" onClick={()=>setComplete(!complete)}><span>✓</span>{complete?"Completed":"Mark as Complete"}<FiBookmark/></button><button className="download-pdf"><FiDownload/> Download PDF</button><div className="side-actions"><button onClick={()=>setSaved(!saved)} className={saved?"saved":""}><FiBookmark/> {saved?"Saved":"Save"}</button><button><FiShare2/> Share</button><button><FiMessageSquare/> Report</button></div></section><section className="viewer-side-card rating-card"><h3>Rate this Resource</h3><div className="stars"><span>★ ★ ★ ★</span><i>☆</i><b>4.7 <small>(430 reviews)</small></b></div></section><section className="viewer-side-card reviews-card"><header><h3><FiMessageSquare/> Reviews</h3><a>View All →</a></header><article><span className="review-avatar purple">A</span><div><b>Anjali Patil</b><div className="review-stars">★★★★</div><p>Very well structured notes with clear explanations and examples. Helpful for exam preparation.</p><small>12 Mar 2025</small></div></article><article><span className="review-avatar dark">R</span><div><b>Rohit Jadhav</b><div className="review-stars">★★★★☆</div><p>Good notes. Diagrams are very helpful. Some more solved examples would be great.</p><small>28 Feb 2025</small></div></article></section><section className="viewer-side-card related-card"><header><h3>Related Resources</h3><a>View All →</a></header><div className="related-row"><span className="related-cover">DBMS</span><div><b>Unit II - Solved Examples</b><small>DBMS · Solutions</small><span>★ 4.6 &nbsp;|&nbsp; 1.8K downloads</span></div><FiDownload/></div><div className="related-row"><span className="related-cover blue">Unit</span><div><b>Normalization Practice Questions</b><small>DBMS · Question Bank</small><span>★ 4.8 &nbsp;|&nbsp; 1.2K downloads</span></div><FiDownload/></div></section></aside>
}
export default function ResourceViewerPage(){
 const {subjectCode,resourceId}=useParams(),subject=getSubject((subjectCode||"DBMS").toUpperCase());
 const resource=useMemo(()=>buildViewerResource(subject,resourceId||""),[subject,resourceId]); const [page,setPage]=useState(15);
 return <div className="resource-viewer-page"><HomeNavbar/><main><div className="viewer-hero"><div className="viewer-breadcrumb"><Link to="/resources">Resources</Link><span>›</span><Link to={"/resources/"+subject.code}>{subject.code}</Link><span>›</span><span>{resource.type}</span><span>›</span><b>{resource.title}</b></div><div className="viewer-resource-head"><div className="viewer-cover"><FiBookOpen/></div><div className="viewer-resource-info"><div className="viewer-title-line"><h1>{resource.title}</h1><label>{resource.type}</label></div><div className="viewer-meta"><span>{subject.code}</span><i/><span>Semester {subject.semester}</span><i/><span>{subject.branch}</span><i/><span>SPPU</span></div><p>{resource.description} Detailed examples, diagrams and practice questions.</p><div className="viewer-facts"><span><FiStar/><b>{resource.rating}</b> ({resource.reviews} reviews)</span><span><FiDownload/>{resource.downloads}</span><span><FiSearch/>2.1K views</span><span><FiCalendar/>Uploaded on 12 Mar 2025</span><span><FiUser/>By Priya Sharma</span><label>Top Contributor</label></div></div></div></div><div className="viewer-workspace"><Outline subject={subject}/><DocumentPreview subject={subject} resource={resource} page={page} setPage={setPage}/><ReadingProgress page={page}/></div></main></div>
}