import {FiBookmark,FiBookOpen,FiDownload,FiFileText,FiSearch,FiStar} from "react-icons/fi";
import {useMemo,useState} from "react";
const toneClass={cream:"cream",blue:"blue",red:"red",green:"green"};
export default function SubjectResourceList({subject}){
 const [query,setQuery]=useState(""); const [bookmarks,setBookmarks]=useState(new Set());
 const filtered=useMemo(()=>subject.resources.filter(r=>(r[0]+" "+r[1]).toLowerCase().includes(query.toLowerCase())),[subject.resources,query]);
 const toggle=title=>setBookmarks(prev=>{const next=new Set(prev);next.has(title)?next.delete(title):next.add(title);return next});
 return <section className="subject-resource-area"><div className="resource-area-heading"><div><span className="subject-section-icon"><FiBookOpen/></span><div><h2>Notes</h2><p>Well-organized notes for easy learning and revision.</p></div></div></div><div className="subject-resource-search"><FiSearch/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={"Search "+subject.code+" notes (e.g. normalization, transactions, SQL)..."}/></div><div className="resource-filter-row"><button>All Units <span>⌄</span></button><button>All Years <span>⌄</span></button><button>File Type <span>⌄</span></button><button>Sort By <span>⌄</span></button></div><div className="subject-resource-list">{filtered.map(([title,description,unit,size,rating,reviews,downloads,type,badge,tone])=><article className="subject-resource-card" key={title}><div className={"resource-cover "+(toneClass[tone]||"blue")}><FiBookOpen/><small>{subject.code}</small></div><div className="resource-card-main"><h3>{title}</h3><p>{description}</p><div className="resource-card-meta"><span><FiFileText/> {unit}</span><span>{size}</span><span>PDF</span><label className="resource-tag blue-tag">{type}</label><label className={"resource-tag "+(badge==="Important"?"red-tag":"green-tag")}>{badge}</label></div></div><div className="resource-card-side"><div><span><FiStar/> {rating} ({reviews})</span><small>{downloads}</small></div><div className="resource-card-actions"><button className={bookmarks.has(title)?"bookmarked":""} onClick={()=>toggle(title)} aria-label="Save resource"><FiBookmark/></button><button aria-label="Download resource"><FiDownload/></button></div></div></article>)}</div><div className="resource-pagination"><span>Showing 1–{filtered.length} of {subject.resources.length} notes</span><div><button>‹</button><button className="active">1</button><button>2</button><button>›</button></div></div></section>
}
